yarnPath: .yarn/releases/yarn-2.1.1.cjs
packageExtensions:
    "@arkecosystem/core-kernel@*":
        dependencies:
            "@arkecosystem/core-logger-pino": "3.0.0-alpha.9"
            "@arkecosystem/core-manager": "3.0.0-alpha.9"
            "@arkecosystem/core-state": "3.0.0-alpha.9"
            "@arkecosystem/core-database": "3.0.0-alpha.9"
            "@arkecosystem/core-transactions": "3.0.0-alpha.9"
            "@arkecosystem/core-magistrate-transactions": "3.0.0-alpha.9"
            "@arkecosystem/core-magistrate-api": "3.0.0-alpha.9"
            "@arkecosystem/core-transaction-pool": "3.0.0-alpha.9"
            "@arkecosystem/core-p2p": "3.0.0-alpha.9"
            "@arkecosystem/core-blockchain": "3.0.0-alpha.9"
            "@arkecosystem/core-api": "3.0.0-alpha.9"
            "@arkecosystem/core-forger": "3.0.0-alpha.9"
            "@arkecosystem/core-webhooks": "3.0.0-alpha.9"
            "@arkecosystem/core-snapshots": "3.0.0-alpha.9"
    "@arkecosystem/core-database@*":
        dependencies:
            "pg": "^8.2.1"
