yarnPath: .yarn/releases/yarn-2.1.1.cjs
packageExtensions:
    "@arkecosystem/core-kernel@*":
        dependencies:
            "@arkecosystem/core-logger-pino": "alpha"
            "@arkecosystem/core-manager": "alpha"
            "@arkecosystem/core-state": "alpha"
            "@arkecosystem/core-database": "alpha"
            "@arkecosystem/core-transactions": "alpha"
            "@arkecosystem/core-magistrate-transactions": "alpha"
            "@arkecosystem/core-magistrate-api": "alpha"
            "@arkecosystem/core-transaction-pool": "alpha"
            "@arkecosystem/core-p2p": "alpha"
            "@arkecosystem/core-blockchain": "alpha"
            "@arkecosystem/core-api": "alpha"
            "@arkecosystem/core-forger": "alpha"
            "@arkecosystem/core-webhooks": "alpha"
            "@arkecosystem/core-snapshots": "alpha"
            "@protokol/nft-base-transactions": "workspace:packages/nft-base-transactions"
            "@protokol/nft-exchange-transactions": "workspace:packages/nft-exchange-transactions"
            "@protokol/guardian-transactions": "workspace:packages/guardian-transactions"
            "@protokol/nft-base-api": "workspace:packages/nft-base-api"
            "@protokol/nft-exchange-api": "workspace:packages/nft-exchange-api"
            "@protokol/guardian-api": "workspace:packages/guardian-api"
    "@arkecosystem/core-database@*":
        dependencies:
            "pg": "latest"
    "@arkecosystem/crypto@*":
        dependencies:
            "@types/node": "latest"
    "@arkecosystem/core-transaction-pool@*":
        dependencies:
            "@arkecosystem/core-magistrate-crypto": "alpha"
    "@types/eslint-plugin-prettier@*":
        dependencies:
            "eslint": "latest"
    "@protokol/nft-base-transactions@*":
        dependencies:
            "ajv": "latest"
    "typeorm@*":
        dependencies:
            "pg-query-stream": "latest"
            "pg": "latest"
    "pg-cursor@*":
        dependencies:
            "pg": "latest"
