packageExtensions:
  "@arkecosystem/core-database@*":
    dependencies:
      pg: latest
  "@arkecosystem/core-kernel@*":
    dependencies:
      "@arkecosystem/core-api": alpha
      "@arkecosystem/core-blockchain": alpha
      "@arkecosystem/core-database": alpha
      "@arkecosystem/core-forger": alpha
      "@arkecosystem/core-logger-pino": alpha
      "@arkecosystem/core-magistrate-api": alpha
      "@arkecosystem/core-magistrate-transactions": alpha
      "@arkecosystem/core-manager": alpha
      "@arkecosystem/core-p2p": alpha
      "@arkecosystem/core-snapshots": alpha
      "@arkecosystem/core-state": alpha
      "@arkecosystem/core-transaction-pool": alpha
      "@arkecosystem/core-transactions": alpha
      "@arkecosystem/core-webhooks": alpha
      "@protokol/guardian-api": "workspace:packages/guardian-api"
      "@protokol/guardian-transactions": "workspace:packages/guardian-transactions"
      "@protokol/nft-base-api": "workspace:packages/nft-base-api"
      "@protokol/nft-base-transactions": "workspace:packages/nft-base-transactions"
      "@protokol/nft-exchange-api": "workspace:packages/nft-exchange-api"
      "@protokol/nft-exchange-transactions": "workspace:packages/nft-exchange-transactions"
  "@arkecosystem/core-transaction-pool@*":
    dependencies:
      "@arkecosystem/core-magistrate-crypto": alpha
  "@arkecosystem/crypto@*":
    dependencies:
      "@types/node": latest
  "@protokol/nft-base-transactions@*":
    dependencies:
      ajv: latest
  "@types/eslint-plugin-prettier@*":
    dependencies:
      eslint: latest
  node-fetch@*:
    dependencies:
      domexception: latest
  pg-cursor@*:
    dependencies:
      pg: latest
  typeorm@*:
    dependencies:
      pg: latest
      pg-query-stream: latest

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
