yarnPath: .yarn/releases/yarn-2.1.1.cjs
packageExtensions:
    "@arkecosystem/core-kernel@*":
        dependencies:
            "@arkecosystem/core-logger-pino": "3.0.0-alpha.10"
            "@arkecosystem/core-manager": "3.0.0-alpha.10"
            "@arkecosystem/core-state": "3.0.0-alpha.10"
            "@arkecosystem/core-database": "3.0.0-alpha.10"
            "@arkecosystem/core-transactions": "3.0.0-alpha.10"
            "@arkecosystem/core-magistrate-transactions": "3.0.0-alpha.10"
            "@arkecosystem/core-magistrate-api": "3.0.0-alpha.10"
            "@arkecosystem/core-transaction-pool": "3.0.0-alpha.10"
            "@arkecosystem/core-p2p": "3.0.0-alpha.10"
            "@arkecosystem/core-blockchain": "3.0.0-alpha.10"
            "@arkecosystem/core-api": "3.0.0-alpha.10"
            "@arkecosystem/core-forger": "3.0.0-alpha.10"
            "@arkecosystem/core-webhooks": "3.0.0-alpha.10"
            "@arkecosystem/core-snapshots": "3.0.0-alpha.10"
            "@protokol/nft-base-transactions": "1.0.0-beta.30"
            "@protokol/nft-base-api": "1.0.0-beta.30"
    "@arkecosystem/core-database@*":
        dependencies:
            "pg": "^8.2.1"
    "@arkecosystem/crypto@*":
        dependencies:
            "@types/node": "^14.11.2"
    "@arkecosystem/core-transaction-pool@*":
        dependencies:
            "@arkecosystem/core-magistrate-crypto": "3.0.0-alpha.10"
