name: Publish To Npm:Beta
on:
  release:
    types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: Install & Build
              run: yarn && yarn build

            - name: Publish to NPM
              run: |
                cd packages
                cd nft-base-crypto && yarn publish:beta && cd ..
                cd nft-base-transactions && yarn publish:beta && cd ..
                cd nft-base-api && yarn publish:beta && cd ..
                cd nft-exchange-crypto && yarn publish:beta && cd ..
                cd nft-exchange-transactions && yarn publish:beta && cd ..
                cd nft-exchange-api && yarn publish:beta && cd ..
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
