name: PUBLISH NPM:BETA
on:
  release:
    types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '12.x'
                  registry-url: https://registry.npmjs.org/
                  always-auth: true

            - name: Install & Build
              run: yarn && yarn build

            - name: Publish to NPM
              run: |
                yarn config set npmAuthToken "$env:NODE_AUTH_TOKEN"
                yarn publish:beta
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN }}
